### ISSUE TITLE
Add support to cache secrets via parameter store

### ISSUE THREAD

**Issue by hariohmprasath** [aws-samples/aws-lambda-extensions#29]
Enhance "cache-extension-demo" lambda extension to cache secrets via parameter store, here is an example configuration.

```yaml
parameters:
  - region: us-east-1
    names:
      - /aws/reference/secretsmanager/abcsecret
```
